import React, { createContext, useContext, useState, useEffect } from 'react'
import { getItem, setItem } from '../utils/storage' // new helper

const LanguageContext = createContext()

export function useLanguage() {
  return useContext(LanguageContext)
}

const translations = {
  en: {
    // Navigation
    home: 'Home',
    dashboard: 'Dashboard',
    profile: 'Profile',
    messages: 'Messages',
    learning: 'Learning',
    quizzes: 'Quizzes',
    tutors: 'Tutors',
    progress: 'Progress',
    students: 'Students',
    resources: 'Resources',
    analytics: 'Analytics',
    settings: 'Settings',
    logout: 'Logout',
    notifications: 'Notifications',
    files: 'Files',
    
    // Auth
    signIn: 'Sign In',
    signUp: 'Sign Up',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    role: 'I am a',
    student: 'Student',
    teacher: 'Teacher',
    admin: 'Admin',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    
    // Dashboard
    welcomeBackUser: 'Welcome back',
    continueJourney: 'Continue your learning journey',
    activeCourses: 'Active Courses',
    overallProgress: 'Overall Progress',
    completedModules: 'Completed Modules',
    quizAverage: 'Quiz Average',
    mySubjects: 'My Subjects',
    continueFromLeft: 'Continue learning from where you left off',
    viewSubjects: 'View Subjects',
    findTutors: 'Find Tutors',
    getHelpFromExperts: 'Get help from expert teachers',
    browseTutors: 'Browse Tutors',
    myProgress: 'My Progress',
    trackAchievements: 'Track your learning achievements',
    viewProgress: 'View Progress',
    chatWithTeachers: 'Chat with teachers and classmates',
    viewMessages: 'View Messages',
    recentActivity: 'Recent Activity',
    noActivitiesYet: 'No activities yet. Start learning to see your progress here!',
    totalStudents: 'Total Students',
    activeClasses: 'Active Classes',
    sessionsThisWeek: 'Sessions This Week',
    averageRating: 'Average Rating',
    teacherDashboard: 'Teacher Dashboard',
    studentProgress: 'Student Progress',
    viewAllStudentPerformance: 'View all student performance',
    viewStudents: 'View Students',
    myClasses: 'My Classes',
    activeClassesCount: 'active classes',
    addNewClass: 'Add New Class',
    assignments: 'Assignments',
    pendingAssignments: 'pending assignments',
    createAssignment: 'Create Assignment',
    noClassesYet: 'No classes yet. Click "Add New Class" to create your first class.',
    students: 'students',
    noPendingAssignments: 'No pending assignments. Click "Create Assignment" to add one.',
    submitted: 'submitted',
    due: 'Due',
    noRecentActivities: 'No recent activities. Start managing your classes to see activity here.',
    adminDashboard: 'Admin Dashboard',
    systemOverview: 'System Overview',
    activeTeachers: 'Active Teachers',
    totalCourses: 'Total Courses',
    completionRate: 'Completion Rate',
    userManagement: 'User Management',
    manageStudentsTeachersAdmins: 'Manage students, teachers, and admins',
    manageUsers: 'Manage Users',
    contentManagement: 'Content Management',
    approveManageMaterials: 'Approve and manage learning materials',
    manageContent: 'Manage Content',
    platformUsageMetrics: 'Platform usage and performance metrics',
    viewAnalytics: 'View Analytics',
    systemSettings: 'System Settings',
    configurePlatformSettings: 'Configure platform settings',
    reports: 'Reports',
    generateSystemReports: 'Generate system reports',
    viewReports: 'View Reports',
    systemAlerts: 'System Alerts',
    activeAlerts: 'active alerts',
    addAlert: 'Add Alert',
    platformStatistics: 'Platform Statistics',
    activeUsersToday: 'Active Users Today',
    coursesCompleted: 'Courses Completed',
    platformAvgScore: 'Platform Avg Score',
    recentRegistrations: 'Recent Registrations',
    noUserRegistrations: 'No user registrations yet.',
    topPerformingSubjects: 'Top Performing Subjects',
    noSubjectData: 'No subject data available yet. Students need to start learning.',
    avg: 'Avg',
    noSystemAlerts: 'No system alerts. Click "Add Alert" to create one.',
    
    // Subjects
    southSudanCurriculum: 'South Sudan National Curriculum',
    grade9and10: 'Grades 9-12',
    compulsorySubjects: 'Compulsory Subjects',
    scienceSubjects: 'Science Subjects',
    artsSubjects: 'Arts Subjects',
    startLearning: 'Start Learning',
    continueLearning: 'Continue Learning',
    notStarted: 'Not Started',
    
    // Profile
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    phone: 'Phone',
    school: 'School',
    grade: 'Grade',
    subject: 'Subject',
    biography: 'Biography',
    links: 'Links',
    contact: 'Contact',
    aboutMe: 'About Me',
    teachingPhilosophy: 'Teaching Philosophy',
    
    // Messages
    newChat: 'New Chat',
    createGroup: 'Create Group',
    groupName: 'Group name',
    selectStudents: 'Select Students',
    typeMessage: 'Type a message...',
    noMessages: 'No messages yet',
    selectConversation: 'Select a conversation to start messaging',
    
    // Quizzes
    takeQuiz: 'Take Quiz',
    createQuiz: 'Create Quiz',
    quizTitle: 'Quiz Title',
    timeLimit: 'Time Limit',
    minutes: 'minutes',
    questions: 'Questions',
    score: 'Score',
    submit: 'Submit',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    submit: 'Submit',
    loading: 'Loading...',
    noData: 'No data available',
    search: 'Search',
    filter: 'Filter',
    view: 'View',
    download: 'Download',
    upload: 'Upload',
    create: 'Create',
    update: 'Update',
    complete: 'Complete',
    members: 'members',
    
    // Auth Pages
    signInToAccount: 'Sign in to your SSPLP account',
    demoAdminAccount: 'Demo Admin Account:',
    enterYourEmail: 'Enter your email',
    enterYourPassword: 'Enter your password',
    signingIn: 'Signing In...',
    pleaseFillAllFields: 'Please fill in all fields',
    joinSSPLP: 'Join SSPLP and start learning today',
    enterFullName: 'Enter your full name',
    createPassword: 'Create a password',
    confirmYourPassword: 'Confirm your password',
    creatingAccount: 'Creating Account...',
    passwordsDoNotMatch: 'Passwords do not match',
    
    // Messages Page
    newChat: 'New Chat',
    direct: 'Direct',
    groups: 'Groups',
    startNewChat: 'Start New Chat',
    createGroup: 'Create Group',
    selectStudents: 'Select Students:',
    noMessagesYet: 'No messages yet',
    noGroupsYet: 'No groups yet',
    typeMessage: 'Type a message...',
    selectConversation: 'Select a conversation to start messaging',
    
    // Profile Page
    editProfile: 'Edit Profile',
    contact: 'Contact',
    aboutMe: 'About Me',
    teachingPhilosophy: 'Teaching Philosophy',
    biography: 'Biography',
    links: 'Links',
    noLinksAdded: 'No links added yet. Edit your profile to add social links.',
    basicInformation: 'Basic Information',
    socialLinks: 'Social Links',
    profilePhoto: 'Profile Photo',
    changePhoto: 'Change Photo',
    saveChanges: 'Save Changes',
    profileUpdated: 'Profile updated successfully!',
    shareLearningGoals: 'Share your learning goals and interests.',
    shareTeachingPhilosophy: 'Share your teaching philosophy and experience.',
    shareKnowledge: 'Share your knowledge and experiences.',
    myFiles: 'My Files',
    allMyFiles: 'All My Files',
    addFolder: 'Add Folder',
    noFilesYet: 'No files or folders yet',
    clickAddFolder: 'Click "Add Folder" above to create your first folder',
    name: 'Name',
    modified: 'Modified',
    size: 'Size',
    actions: 'Actions',
    notificationSettings: 'Notification Settings',
    updatePreferences: 'Update Preferences',
    updateSettings: 'Update Settings',
    selectGrade: 'Select Grade',
    subjectSpecialization: 'Subject Specialization',
    systemAlerts: 'System Alerts',
    admin: 'Admin',
    user: 'User',
    
    // Subjects Page
    mySubjects: 'My Subjects',
    southSudanCurriculum: 'South Sudan National Curriculum',
    compulsorySubjects: 'Compulsory Subjects',
    scienceSection: 'Science Section',
    artsSection: 'Arts Section',
    
    // Progress Page
    myProgress: 'My Progress',
    trackLearningJourney: 'Track your learning journey',
    overallProgress: 'Overall Progress',
    completedSubjects: 'Completed Subjects',
    activeSubjects: 'Active Subjects',
    subjectProgress: 'Subject Progress',
    recentActivity: 'Recent Activity',
    noActivitiesYet: 'No activities yet. Start learning to see your progress here!',
    
    // Tutors Page
    findATutor: 'Find a Tutor',
    connectWithExperts: 'Connect with expert teachers',
    noTeachersAvailable: 'No teachers available yet',
    messageTeacher: 'Message Teacher',
    groupMembers: 'Group Members',
    learningResources: 'Learning Resources',
    subjectCompleted: 'Subject Completed!',
    resources: 'resources',
    videos: 'videos',
    documents: 'documents',
    showing: 'Showing',
    of: 'of',
    loadMore: 'Load More',
    backToResources: 'Back to Resources',
    watch: 'Watch',
    view: 'View',
    
    // Subject Names
    mathematics: 'Mathematics',
    english: 'English',
    religion: 'Religion',
    citizenship: 'Citizenship',
    biology: 'Biology',
    physics: 'Physics',
    chemistry: 'Chemistry',
    agriculture: 'Agriculture',
    additionalMathematics: 'Additional Mathematics',
    ict: 'ICT',
    history: 'History',
    geography: 'Geography',
    commerce: 'Commerce',
    accounting: 'Accounting',
    literature: 'Literature',
    
    // Analytics Page
    platformAnalytics: 'Platform Analytics',
    comprehensiveMetrics: 'Comprehensive platform usage and performance metrics',
    userOverview: 'User Overview',
    totalUsers: 'Total Users',
    engagementRate: 'Engagement Rate',
    learningMetrics: 'Learning Metrics',
    totalQuizzes: 'Total Quizzes',
    quizzesCompleted: 'Quizzes Completed',
    avgQuizScore: 'Avg Quiz Score',
    learningResources: 'Learning Resources',
    resourcesByType: 'Resources by Type',
    documents: 'Documents',
    videos: 'Videos',
    audio: 'Audio',
    links: 'Links',
    communicationMetrics: 'Communication Metrics',
    totalMessages: 'Total Messages',
    messagesThisWeek: 'Messages This Week',
    activeConversations: 'Active Conversations',
    topPerformingSubjects: 'Top Performing Subjects',
    noDataAvailable: 'No data available yet',
    
    // Home Page
    heroTitle: 'Transforming Education in South Sudan',
    heroSubtitle: 'Personalized learning, qualified tutors, and curriculum-aligned resources—all in one platform.',
    goToDashboard: 'Go to Dashboard',
    curriculumTitle: 'South Sudan National Curriculum',
    curriculumSubtitle: 'All 15 subjects aligned with national standards',
    compulsorySubjectsCount: 'Compulsory Subjects (4)',
    compulsorySubjectsList: 'Mathematics, English, Religion, Citizenship',
    scienceSectionCount: 'Science Section (6)',
    scienceSectionList: 'Biology, Physics, Chemistry, Agriculture, Additional Mathematics, ICT',
    artsSectionCount: 'Arts Section (5)',
    artsSectionList: 'History, Geography, Commerce, Accounting, Literature',
    featuresTitle: 'Everything You Need for Academic Success',
    personalizedLearning: 'Personalized Learning',
    personalizedLearningDesc: "Adaptive learning paths tailored to each student's level",
    expertTutoring: 'Expert Tutoring',
    expertTutoringDesc: 'Connect with qualified South Sudanese teachers',
    offlineAccess: 'Offline Access',
    offlineAccessDesc: 'Learn anywhere, anytime, even without internet',
    multiLanguage: 'Multi-Language',
    multiLanguageDesc: 'Available in English and Arabic',
    ctaTitle: 'Ready to Transform Your Learning Journey?',
    ctaSubtitle: 'Join thousands of students across South Sudan achieving academic success with SSPLP.',
    continueLearning: 'Continue Learning',
    platformDescription: 'South Sudan Personalized Learning Platform - Transforming education through technology.',
    quickLinks: 'Quick Links',
    contact: 'Contact',
    allRightsReserved: 'All rights reserved',
    
    // New Features
    performanceReports: 'Performance Reports',
    monthlyReport: 'Monthly Report',
    termlyReport: 'Termly Report',
    averageScore: 'Average Score',
    needsImprovement: 'Needs Improvement',
    recommendations: 'Recommendations',
    markAllRead: 'Mark All Read',
    noNotifications: 'No notifications yet',
    virtualTutoring: 'Virtual Tutoring',
    scheduleSession: 'Schedule Session',
    noSessionsScheduled: 'No sessions scheduled yet',
    sessionTitle: 'Session Title',
    groupSession: 'Group Session',
    individualSession: 'Individual Session',
    joinSession: 'Join Session',
    completeSession: 'Complete Session',
    selectTeacher: 'Select Teacher',
    schedule: 'Schedule',
    dailyNewsletter: 'Daily Newsletter',
    newsletterDescription: 'Subscribe to get daily education news and updates',
    successfullySubscribed: 'Successfully subscribed!',
  },
  ar: {
    // Navigation
    home: 'الرئيسية',
    dashboard: 'لوحة التحكم',
    profile: 'الملف الشخصي',
    messages: 'الرسائل',
    learning: 'التعلم',
    quizzes: 'الاختبارات',
    tutors: 'المعلمون',
    progress: 'التقدم',
    students: 'الطلاب',
    resources: 'الموارد',
    analytics: 'التحليلات',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    notifications: 'الإشعارات',
    files: 'الملفات',
    
    // Auth
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    welcomeBack: 'مرحباً بعودتك',
    createAccount: 'إنشاء حساب جديد',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    fullName: 'الاسم الكامل',
    role: 'أنا',
    student: 'طالب',
    teacher: 'معلم',
    admin: 'مسؤول',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    
    // Dashboard
    welcomeBackUser: 'مرحباً بعودتك',
    continueJourney: 'تابع رحلتك التعليمية',
    activeCourses: 'الدورات النشطة',
    overallProgress: 'التقدم الإجمالي',
    completedModules: 'الوحدات المكتملة',
    quizAverage: 'متوسط الاختبارات',
    mySubjects: 'موادي',
    continueFromLeft: 'تابع التعلم من حيث توقفت',
    viewSubjects: 'عرض المواد',
    findTutors: 'البحث عن معلمين',
    getHelpFromExperts: 'احصل على المساعدة من معلمين خبراء',
    browseTutors: 'تصفح المعلمين',
    myProgress: 'تقدمي',
    trackAchievements: 'تتبع إنجازاتك التعليمية',
    viewProgress: 'عرض التقدم',
    chatWithTeachers: 'الدردشة مع المعلمين والزملاء',
    viewMessages: 'عرض الرسائل',
    recentActivity: 'النشاط الأخير',
    noActivitiesYet: 'لا توجد أنشطة بعد. ابدأ التعلم لرؤية تقدمك هنا!',
    totalStudents: 'إجمالي الطلاب',
    activeClasses: 'الفصول النشطة',
    sessionsThisWeek: 'جلسات هذا الأسبوع',
    averageRating: 'متوسط التقييم',
    teacherDashboard: 'لوحة تحكم المعلم',
    studentProgress: 'تقدم الطلاب',
    viewAllStudentPerformance: 'عرض أداء جميع الطلاب',
    viewStudents: 'عرض الطلاب',
    myClasses: 'فصولي',
    activeClassesCount: 'فصول نشطة',
    addNewClass: 'إضافة فصل جديد',
    assignments: 'الواجبات',
    pendingAssignments: 'واجبات معلقة',
    createAssignment: 'إنشاء واجب',
    noClassesYet: 'لا توجد فصول بعد. انقر على "إضافة فصل جديد" لإنشاء فصلك الأول.',
    students: 'طلاب',
    noPendingAssignments: 'لا توجد واجبات معلقة. انقر على "إنشاء واجب" لإضافة واحد.',
    submitted: 'تم التسليم',
    due: 'الموعد النهائي',
    noRecentActivities: 'لا توجد أنشطة حديثة. ابدأ بإدارة فصولك لرؤية النشاط هنا.',
    adminDashboard: 'لوحة تحكم المسؤول',
    systemOverview: 'نظرة عامة على النظام',
    activeTeachers: 'المعلمون النشطون',
    totalCourses: 'إجمالي الدورات',
    completionRate: 'معدل الإنجاز',
    userManagement: 'إدارة المستخدمين',
    manageStudentsTeachersAdmins: 'إدارة الطلاب والمعلمين والمسؤولين',
    manageUsers: 'إدارة المستخدمين',
    contentManagement: 'إدارة المحتوى',
    approveManageMaterials: 'الموافقة على وإدارة المواد التعليمية',
    manageContent: 'إدارة المحتوى',
    platformUsageMetrics: 'مقاييس استخدام المنصة والأداء',
    viewAnalytics: 'عرض التحليلات',
    systemSettings: 'إعدادات النظام',
    configurePlatformSettings: 'تكوين إعدادات المنصة',
    reports: 'التقارير',
    generateSystemReports: 'إنشاء تقارير النظام',
    viewReports: 'عرض التقارير',
    systemAlerts: 'تنبيهات النظام',
    activeAlerts: 'تنبيهات نشطة',
    addAlert: 'إضافة تنبيه',
    platformStatistics: 'إحصائيات المنصة',
    activeUsersToday: 'المستخدمون النشطون اليوم',
    coursesCompleted: 'الدورات المكتملة',
    platformAvgScore: 'متوسط درجات المنصة',
    recentRegistrations: 'التسجيلات الأخيرة',
    noUserRegistrations: 'لا توجد تسجيلات مستخدمين بعد.',
    topPerformingSubjects: 'المواد الأفضل أداءً',
    noSubjectData: 'لا توجد بيانات مواد بعد. يحتاج الطلاب إلى بدء التعلم.',
    avg: 'متوسط',
    noSystemAlerts: 'لا توجد تنبيهات نظام. انقر على "إضافة تنبيه" لإنشاء واحد.',
    
    // Subjects
    southSudanCurriculum: 'المنهج الوطني لجنوب السودان',
    grade9and10: 'الصفوف 9-12',
    compulsorySubjects: 'المواد الإلزامية',
    scienceSubjects: 'المواد العلمية',
    artsSubjects: 'المواد الأدبية',
    startLearning: 'ابدأ التعلم',
    continueLearning: 'متابعة التعلم',
    notStarted: 'لم يبدأ',
    
    // Profile
    editProfile: 'تعديل الملف الشخصي',
    saveChanges: 'حفظ التغييرات',
    phone: 'الهاتف',
    school: 'المدرسة',
    grade: 'الصف',
    subject: 'المادة',
    biography: 'السيرة الذاتية',
    links: 'الروابط',
    contact: 'الاتصال',
    aboutMe: 'عني',
    teachingPhilosophy: 'فلسفة التدريس',
    
    // Messages
    newChat: 'محادثة جديدة',
    createGroup: 'إنشاء مجموعة',
    groupName: 'اسم المجموعة',
    selectStudents: 'اختر الطلاب',
    typeMessage: 'اكتب رسالة...',
    noMessages: 'لا توجد رسائل بعد',
    selectConversation: 'اختر محادثة لبدء المراسلة',
    
    // Quizzes
    takeQuiz: 'خذ الاختبار',
    createQuiz: 'إنشاء اختبار',
    quizTitle: 'عنوان الاختبار',
    timeLimit: 'الوقت المحدد',
    minutes: 'دقائق',
    questions: 'الأسئلة',
    score: 'النتيجة',
    submit: 'إرسال',
    
    // Common
    save: 'حفظ',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    submit: 'إرسال',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات',
    search: 'بحث',
    filter: 'تصفية',
    view: 'عرض',
    download: 'تحميل',
    upload: 'رفع',
    create: 'إنشاء',
    update: 'تحديث',
    complete: 'مكتمل',
    members: 'أعضاء',
    
    // Auth Pages
    signInToAccount: 'تسجيل الدخول إلى حساب SSPLP',
    demoAdminAccount: 'حساب مسؤول تجريبي:',
    enterYourEmail: 'أدخل بريدك الإلكتروني',
    enterYourPassword: 'أدخل كلمة المرور',
    signingIn: 'جاري تسجيل الدخول...',
    pleaseFillAllFields: 'يرجى ملء جميع الحقول',
    joinSSPLP: 'انضم إلى SSPLP وابدأ التعلم اليوم',
    enterFullName: 'أدخل اسمك الكامل',
    createPassword: 'أنشئ كلمة مرور',
    confirmYourPassword: 'أكد كلمة المرور',
    creatingAccount: 'جاري إنشاء الحساب...',
    passwordsDoNotMatch: 'كلمات المرور غير متطابقة',
    
    // Messages Page
    newChat: 'محادثة جديدة',
    direct: 'مباشر',
    groups: 'مجموعات',
    startNewChat: 'بدء محادثة جديدة',
    createGroup: 'إنشاء مجموعة',
    selectStudents: 'اختر الطلاب:',
    noMessagesYet: 'لا توجد رسائل بعد',
    noGroupsYet: 'لا توجد مجموعات بعد',
    typeMessage: 'اكتب رسالة...',
    selectConversation: 'اختر محادثة لبدء المراسلة',
    
    // Profile Page
    editProfile: 'تعديل الملف الشخصي',
    contact: 'الاتصال',
    aboutMe: 'عني',
    teachingPhilosophy: 'فلسفة التدريس',
    biography: 'السيرة الذاتية',
    links: 'الروابط',
    noLinksAdded: 'لم تتم إضافة روابط بعد. عدل ملفك الشخصي لإضافة روابط اجتماعية.',
    basicInformation: 'المعلومات الأساسية',
    socialLinks: 'الروابط الاجتماعية',
    profilePhoto: 'صورة الملف الشخصي',
    changePhoto: 'تغيير الصورة',
    saveChanges: 'حفظ التغييرات',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
    shareLearningGoals: 'شارك أهدافك واهتماماتك التعليمية.',
    shareTeachingPhilosophy: 'شارك فلسفتك وخبرتك في التدريس.',
    shareKnowledge: 'شارك معرفتك وخبراتك.',
    myFiles: 'ملفاتي',
    allMyFiles: 'جميع ملفاتي',
    addFolder: 'إضافة مجلد',
    noFilesYet: 'لا توجد ملفات أو مجلدات بعد',
    clickAddFolder: 'انقر على "إضافة مجلد" أعلاه لإنشاء مجلدك الأول',
    name: 'الاسم',
    modified: 'معدل',
    size: 'الحجم',
    actions: 'الإجراءات',
    notificationSettings: 'إعدادات الإشعارات',
    updatePreferences: 'تحديث التفضيلات',
    updateSettings: 'تحديث الإعدادات',
    selectGrade: 'اختر الصف',
    subjectSpecialization: 'التخصص في المادة',
    systemAlerts: 'تنبيهات النظام',
    admin: 'مسؤول',
    user: 'مستخدم',
    
    // Subjects Page
    mySubjects: 'موادي',
    southSudanCurriculum: 'المنهج الوطني لجنوب السودان',
    compulsorySubjects: 'المواد الإلزامية',
    scienceSection: 'قسم العلوم',
    artsSection: 'قسم الآداب',
    
    // Progress Page
    myProgress: 'تقدمي',
    trackLearningJourney: 'تتبع رحلتك التعليمية',
    overallProgress: 'التقدم الإجمالي',
    completedSubjects: 'المواد المكتملة',
    activeSubjects: 'المواد النشطة',
    subjectProgress: 'تقدم المواد',
    recentActivity: 'النشاط الأخير',
    noActivitiesYet: 'لا توجد أنشطة بعد. ابدأ التعلم لرؤية تقدمك هنا!',
    
    // Tutors Page
    findATutor: 'ابحث عن معلم',
    connectWithExperts: 'تواصل مع معلمين خبراء',
    noTeachersAvailable: 'لا يوجد معلمون متاحون بعد',
    messageTeacher: 'مراسلة المعلم',
    groupMembers: 'أعضاء المجموعة',
    learningResources: 'موارد التعلم',
    subjectCompleted: 'اكتمل الموضوع!',
    resources: 'موارد',
    videos: 'فيديوهات',
    documents: 'مستندات',
    showing: 'عرض',
    of: 'من',
    loadMore: 'تحميل المزيد',
    backToResources: 'العودة إلى الموارد',
    watch: 'مشاهدة',
    view: 'عرض',
    
    // Subject Names
    mathematics: 'الرياضيات',
    english: 'الإنجليزية',
    religion: 'الدين',
    citizenship: 'المواطنة',
    biology: 'الأحياء',
    physics: 'الفيزياء',
    chemistry: 'الكيمياء',
    agriculture: 'الزراعة',
    additionalMathematics: 'الرياضيات الإضافية',
    ict: 'تكنولوجيا المعلومات',
    history: 'التاريخ',
    geography: 'الجغرافيا',
    commerce: 'التجارة',
    accounting: 'المحاسبة',
    literature: 'الأدب',
    
    // Analytics Page
    platformAnalytics: 'تحليلات المنصة',
    comprehensiveMetrics: 'مقاييس شاملة لاستخدام وأداء المنصة',
    userOverview: 'نظرة عامة على المستخدمين',
    totalUsers: 'إجمالي المستخدمين',
    engagementRate: 'معدل المشاركة',
    learningMetrics: 'مقاييس التعلم',
    totalQuizzes: 'إجمالي الاختبارات',
    quizzesCompleted: 'الاختبارات المكتملة',
    avgQuizScore: 'متوسط درجة الاختبار',
    learningResources: 'موارد التعلم',
    resourcesByType: 'الموارد حسب النوع',
    documents: 'المستندات',
    videos: 'الفيديوهات',
    audio: 'الصوتيات',
    links: 'الروابط',
    communicationMetrics: 'مقاييس الاتصال',
    totalMessages: 'إجمالي الرسائل',
    messagesThisWeek: 'رسائل هذا الأسبوع',
    activeConversations: 'المحادثات النشطة',
    topPerformingSubjects: 'المواد الأفضل أداءً',
    noDataAvailable: 'لا توجد بيانات متاحة بعد',
    
    // Home Page
    heroTitle: 'تحويل التعليم في جنوب السودان',
    heroSubtitle: 'تعلم شخصي، معلمون مؤهلون، وموارد متوافقة مع المنهج - كل ذلك في منصة واحدة.',
    goToDashboard: 'اذهب إلى لوحة التحكم',
    curriculumTitle: 'المنهج الوطني لجنوب السودان',
    curriculumSubtitle: 'جميع المواد الـ 15 متوافقة مع المعايير الوطنية',
    compulsorySubjectsCount: 'المواد الإلزامية (4)',
    compulsorySubjectsList: 'الرياضيات، الإنجليزية، الدين، المواطنة',
    scienceSectionCount: 'قسم العلوم (6)',
    scienceSectionList: 'الأحياء، الفيزياء، الكيمياء، الزراعة، الرياضيات الإضافية، تكنولوجيا المعلومات',
    artsSectionCount: 'قسم الآداب (5)',
    artsSectionList: 'التاريخ، الجغرافيا، التجارة، المحاسبة، الأدب',
    featuresTitle: 'كل ما تحتاجه للنجاح الأكاديمي',
    personalizedLearning: 'تعلم شخصي',
    personalizedLearningDesc: 'مسارات تعليمية تكيفية مصممة حسب مستوى كل طالب',
    expertTutoring: 'تدريس متخصص',
    expertTutoringDesc: 'تواصل مع معلمين مؤهلين من جنوب السودان',
    offlineAccess: 'الوصول دون اتصال',
    offlineAccessDesc: 'تعلم في أي مكان وزمان، حتى بدون إنترنت',
    multiLanguage: 'متعدد اللغات',
    multiLanguageDesc: 'متوفر باللغتين الإنجليزية والعربية',
    ctaTitle: 'هل أنت مستعد لتحويل رحلتك التعليمية؟',
    ctaSubtitle: 'انضم إلى آلاف الطلاب في جنوب السودان الذين يحققون النجاح الأكاديمي مع SSPLP.',
    continueLearning: 'متابعة التعلم',
    platformDescription: 'منصة التعلم الشخصي لجنوب السودان - تحويل التعليم من خلال التكنولوجيا.',
    quickLinks: 'روابط سريعة',
    contact: 'اتصل بنا',
    allRightsReserved: 'جميع الحقوق محفوظة',
    
    // New Features
    performanceReports: 'تقارير الأداء',
    monthlyReport: 'تقرير شهري',
    termlyReport: 'تقرير فصلي',
    averageScore: 'متوسط الدرجات',
    needsImprovement: 'يحتاج إلى تحسين',
    recommendations: 'التوصيات',
    markAllRead: 'وضع علامة مقروء على الكل',
    noNotifications: 'لا توجد إشعارات بعد',
    virtualTutoring: 'التدريس الافتراضي',
    scheduleSession: 'جدولة جلسة',
    noSessionsScheduled: 'لا توجد جلسات مجدولة بعد',
    sessionTitle: 'عنوان الجلسة',
    groupSession: 'جلسة جماعية',
    individualSession: 'جلسة فردية',
    joinSession: 'انضم للجلسة',
    completeSession: 'إكمال الجلسة',
    selectTeacher: 'اختر المعلم',
    schedule: 'جدولة',
    dailyNewsletter: 'النشرة الإخبارية اليومية',
    newsletterDescription: 'اشترك للحصول على أخبار وتحديثات التعليم اليومية',
    subscribe: 'اشترك',
    successfullySubscribed: 'تم الاشتراك بنجاح!',
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  useEffect(() => {
    (async () => {
      // read from storage helper (localStorage or IndexedDB fallback)
      const saved = await getItem('ssplp_language')
      const savedLang = saved || 'en'
      setLanguage(savedLang)
      document.documentElement.lang = savedLang
      document.documentElement.dir = savedLang === 'ar' ? 'rtl' : 'ltr'
    })()
  }, [])

  const changeLanguage = (lang) => {
    setLanguage(lang)
    // async write; no need to await in UI thread
    setItem('ssplp_language', lang).catch(() => {
      /* already handled inside helper */
    })
    document.documentElement.lang = lang
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
  }

  const t = (key) => {
    return translations[language][key] || key
  }

  const value = { language, changeLanguage, t }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
